name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.23.0"
      - name: Install dependencies
        run: |
          go version
      - name: Run build
        run: go build .
      - name: Run vet
        run: |
          go vet .
      - name: Checkout
        uses: actions/checkout@v2
        id: "test"
      - name: Run tests
        run: go test .

