name: Build

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.23.0"
      - name: Current Go Version
        run: go version
      - name: Run vet
        run: go vet ./...
      - name: Run tests
        run: go test ./...

